apiVersion: v1
kind: Service
metadata:
  name: devopsproject5
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: devopsproject5
    version: ${LABEL_VERSION}
  type: LoadBalancer